#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'

ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', File.dirname(__FILE__))

require 'rubygems'
require 'bundler/setup'

require 'pry'

$LOAD_PATH << 'lib'
require 'lograge'

Pry::CLI.parse_options
