#!/usr/bin/env ruby

require 'pathname'

ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', Pathname.new(__FILE__).realpath)

require 'rubygems'
require 'bundler/setup'

require 'pry'

$LOAD_PATH << 'lib'
require 'lograge'

Pry::CLI.parse_options
